apiVersion: apps/v1
kind: Deployment
metadata:
  name: jlox-frontend
  labels:
    app: jlox-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jlox-frontend
  template:
    metadata:
      labels:
        app: jlox-frontend
    spec:
      containers:
      - name: frontend
        image: jlox-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"

