apiVersion: v1
kind: Service
metadata:
  name: jlox-frontend-service
  labels:
    app: jlox-frontend
spec:
  type: LoadBalancer  # Use NodePort for minikube, LoadBalancer for EKS
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: jlox-frontend

